### ISSUE TITLE
Missing path (...SpotImCore.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs) from XCFramework 'SpotImCore.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file

### ISSUE THREAD

**Issue by master-nevi** [SpotIM/spotim-ios-sdk-pod#18]
I get the following error when attempting to use the SpotImCore Swift Package in my project. 

![Screen Shot 2022-09-26 at 9 34 48 PM](https://user-images.githubusercontent.com/987706/192433243-f061201a-9550-420e-b14a-1653fe46232b.png)

When I manually remove the `DebugSymbolsPath` key and `dSYMs` value from the root `Info.plist` [here](https://github.com/SpotIM/spotim-ios-sdk-pod/blob/master/SpotImCore.xcframework/Info.plist#L25), it seems to build. Why is that `DebugSymbolsPath` key even there if the `dSYMs` directory doesn't exist or were removed?

Xcode Version: 13.0

**Comment by master-nevi** [comment]
I think to omit the debug symbols when creating the framework, you just wouldn't use the `-debug-symbols` parameter in the `xcodebuild -create-xcframework` command.

**Comment by master-nevi** [comment]
cc @alon-ha

**Comment by master-nevi** [comment]
Confirmed that version `1.16.2` is the first version that omitted the dSYMs, `1.16.1` did have them:

## 1.16.1
https://github.com/SpotIM/spotim-ios-sdk-pod/tree/1.16.1/SpotImCore.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs

## 1.16.2 (doesn't exist)
https://github.com/SpotIM/spotim-ios-sdk-pod/tree/1.16.2/SpotImCore.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs

**Comment by master-nevi** [comment]
This `.gitignore` line might be the culprit: https://github.com/SpotIM/spotim-ios-sdk-pod/blob/master/.gitignore#L28

**Comment by alon-ha** [comment]
Issue solved with the latest version release
