### ISSUE TITLE
Swift Package builder error: "this SDK is not supported by the compiler"

### ISSUE THREAD

**Issue by master-nevi** [SpotIM/spotim-ios-sdk-pod#19]
I get the following error when attempting to use the SpotImCore Swift Package in my project when building with a version of Xcode other than exactly 13.0 which had the Swift 5.5 compiler:

![Screen Shot 2022-09-26 at 10 58 05 PM](https://user-images.githubusercontent.com/987706/192445656-57410990-26a1-4d50-9d36-347358593703.png)

```
Failed to build module 'SpotImCore'; this SDK is not supported by the compiler
 (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)',
while this compiler is 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)'). 
Please select a toolchain which matches the SDK.
```

The only solution was to build with Xcode 13.0 only which isn't an option for us.

**Comment by master-nevi** [comment]
I managed to work around this by including the `RxCocoaRuntime.xcframework` in the project. For some reason it's not included with the `RxCocoa` Swift package library.

**Comment by master-nevi** [comment]
cc @alon-ha

**Comment by master-nevi** [comment]
@alon-ha Does this error not come up in any of your demo apps that use SPM? Seems like a pretty significant issue to investigate. RxSwift didn't even ship the `RxCocoaRuntime.xcframework` as part of their v6.5 release, see for your self: https://github.com/ReactiveX/RxSwift/releases/download/6.5.0/RxSwift.xcframework.zip doesn't contain `RxCocoaRuntime`. They may have stopped supporting it.

**Comment by alon-ha** [comment]
No, it didn't came up before. You had to use a specific Xcode version release in SPM, however it worked.
Broke for an entire different reason in the latest version.

In the following version SPM integration will be fixed. We are also working on automation to test SPM integration after each version release.

**Comment by marcod-onefootball** [comment]
@alon-ha has this issue been fixed in latest versions? I'm trying to use SPM with the tag `1.18.3-xcode14.3.0` for Xcode 14.3 and I'm also getting this error when building the app:
```
Missing required module 'RxCocoaRuntime'
```

**Comment by alon-ha** [comment]
@marcod-onefootball We successfully validated that this version compile with SPM on a project example with the corresponding tag for the Xcode version. I suggest trying the [solution](https://github.com/SpotIM/spotim-ios-sdk-pod/issues/19#issuecomment-1260167795) above if you still have issues.
Also please contact [publisherfirst@openweb.com](mailto:publisherfirst@openweb.com) for further questions as we are not using Github Issues/comments.
Thank you!
