### ISSUE TITLE
Xcode 14.3 support

### ISSUE THREAD

**Issue by v3trax** [SpotIM/spotim-ios-sdk-pod#24]
Would like to request support for Xcode 14.3 along with -

- Manual integration support for the SDK
- If possible remove RX dependency

Currently, we do not support pod integration and only manual or SPM. 

Veer Busani
Lead iOS Engineer
Fox News/Business/Weather

**Comment by alon-ha** [comment]
We support Xcode 14.3.
For Cocoapods tags are not required. See [here](https://developers.openweb.com/docs/ios-debugging-and-logs#xcode-build-fails-with-error).
For SPM tags are required. We just released latests version in 14.3 [tag](https://github.com/SpotIM/spotim-ios-sdk-pod/releases/tag/1.18.3-xcode14.3.0).

RX dependency won't be removed and required inside our SDK.
