### ISSUE TITLE
Duplicated target name with other packages of SPM

### ISSUE THREAD

**Issue by lisandro** [SpotIM/spotim-ios-sdk-pod#27]
Hello team, I would like to report that installing the SDK by Swift Package Manager can cause a build error because another package is already using a target with the same name https://github.com/SpotIM/spotim-ios-sdk-pod/blob/master/Package.swift#L26

Error:

```
multiple targets named 'WrapperSPMTarget' in: ..... ; consider using the `moduleAliases` parameter in manifest to provide unique names
```

Can you update to have a unique name like `OpenWebWrapperSPMTarget` ?

Thanks

**Comment by alonshp** [comment]
@lisandro We will use a unique name in our next release.
